# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /

# Base Image
FROM ghcr.io/secureblue/kinoite-main-hardened:latest

## Other possible base images include:
# FROM ghcr.io/ublue-os/bazzite:latest
# FROM ghcr.io/ublue-os/bluefin-nvidia:stable
#
# ... and so on, here are more base images
# Universal Blue Images: https://github.com/orgs/ublue-os/packages
# Fedora base image: quay.io/fedora/fedora-bootc:41
# CentOS base images: quay.io/centos-bootc/centos-bootc:stream10

### MODIFICATIONS
## make modifications desired in your image and install packages by modifying the build.sh script
## the following RUN directive does all the things required to run "build.sh" as recommended.

# some T2 tweaks require etc drop-ins
COPY --chmod=0644 /variants/common/etc/ /etc/

# Must be added before T2 kernel install so dracut includes it in the initramfs
RUN echo 'install_items+=" /usr/lib64/libno_rlimit_as.so /usr/lib/systemd/systemd-sysroot-fstab-check /usr/lib/systemd/system-generators/systemd-fstab-generator "' > /etc/dracut.conf.d/99-secureblue-initramfs.conf

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/var \
    /ctx/t2-enablement.sh && \
    rm -rf /tmp/* /var/tmp/* && \
    ostree container commit

ARG USER=secureblue
ARG PASSWORD=secureblue
RUN useradd -m -G wheel $USER && echo "$USER:$PASSWORD" | chpasswd
RUN systemctl set-default graphical.target

### LINTING
## Verify final image and contents are correct.
RUN bootc container lint

# Define required labels for this bootc image to be recognized as such.
LABEL containers.bootc 1
LABEL ostree.bootable 1
